## Configuration
wikiMode: false
noFaq: true

# Colors
primaryColor: '#8BE9FD'
secondaryColor: '#FF2D9A'
textLightColor: '#FFFFFF'
textDarkColor: '#333333'
backgroundLightColor: '#FFFFFF'
backgroundDarkColor: '#1A2A3A'

# Images
logo: /img/logo.png
