## Configuration
wikiMode: true
noFaq: true

# Colors
primaryColor: '#8be9fd'
secondaryColor: '#ff2d9a'
textLightColor: '#eeeeee'
textDarkColor: '#333333'
backgroundLightColor: '#eeeeee'
backgroundDarkColor: '#1a2a3a'

# Images
logo: /img/logo.png