home: home
categories: categories
footerText: Blog done with HTML, CSS, <a href='https://hexo.io' target='_blank'>Hexo</a> and <i class="icon-heart"></i>  
curiosityOfHowWasMade: Curious of how this blog was made? 
accessRepo: Access it's repo
backToTop: Back to top
part: part
tableOfContents: Table of Contents
next: next
previous: previous
postMusic: Music of the Post
hearIt: Hear it